In [164]:
def reto_4(diccionario: dict) -> tuple:
    
    import numpy as np 
    
    if type(diccionario) is not dict:
         return (None,None,None,None,None)

    if (diccionario != None and len(diccionario) > 0)  and (diccionario != None):

        dict_pasantes = list(diccionario.keys())
        resultados = []

        for i in dict_pasantes:
            calificaciones_pasante = []
            for x in diccionario[i].values():
                if type(x) is int:
                    calificaciones_pasante.append(x)
                else:
                    return (None,None,None,None,None)
            
            resultados.append(calificaciones_pasante)

        normalizar = []

        for i in resultados:
            datos_normalizados = list(map(lambda valor: valor if valor >= 5 else 5, i))
            normalizar.append(datos_normalizados)

        matriz = np.array(normalizar)
        
        promedio = np.average(matriz, axis = 0)
        promedio = np.around(promedio, decimals = 1)

        puntaje = np.sum(matriz, axis = 1)

        seleccionado = dict_pasantes[puntaje.argmax()]

        tupla = tuple()
        tupla = (normalizar, matriz, promedio, puntaje, seleccionado)

    else:

        tupla = (None,None,None,None,None)

    return tupla



In [170]:
pasantes = {
    'John': {'prueba 1': 8, 'prueba 2': 7, 'prueba 3': 9}, 
    'Luis': {'prueba 1': 5, 'prueba 2': 7, 'prueba 3': 9}, 
    'Ana': {'prueba 1': 6, 'prueba 2': 7, 'prueba 3': 9}
    }
a,b,c, d, e = reto_4(pasantes)
a = f"Resultados: {a}"
b = f"Matriz: \n{b}"
c = f"Promedio: {c}"
d = f"Puntaje: {d}"
e = f"Seleccionado: {e}"
print(a,b,c,d,e,sep="\n")



Resultados: [[8, 7, 9], [5, 7, 9], [6, 7, 9]]
Matriz: 
[[8 7 9]
 [5 7 9]
 [6 7 9]]
Promedio: [6.3 7.  9. ]
Puntaje: [24 21 22]
Seleccionado: John


In [154]:
pasantes = {'Abril': {'prueba 1': 8, 'prueba 2': 7, 'prueba 3': 9}, 'Pedro': {
'prueba 1': 8, 'prueba 2': 7, 'prueba 3': 9}, 'Rafael': {'prueba 1': 6, 'prueba 2': 7, 'prueba 3': 9}}
a, b, c, d, e = reto_4(pasantes)
a = f"Resultados: {a}"
b = f"Matriz: \n{b}"
c = f"Promedio: {c}"
d = f"Puntajes: {d}"
e = f"Seleccionado: {e}"
print(a, b, c, d, e, sep='\n')

Resultados: [[8, 7, 9], [8, 7, 9], [6, 7, 9]]
Matriz: 
[[8 7 9]
 [8 7 9]
 [6 7 9]]
Promedio: [7.3 7.  9. ]
Puntajes: [24 24 22]
Seleccionado: Abril


In [155]:
pasantes = {'Jose': {'prueba 1': 8, 'prueba 2': 7, 'prueba 3': 9}}
a, b, c, d, e = reto_4(pasantes)
a = f"Resultados: {a}"
b = f"Matriz: \n{b}"
c = f"Promedio: {c}"
d = f"Puntajes: {d}"
e = f"Seleccionado: {e}"
print(a, b, c, d, e, sep='\n')

Resultados: [[8, 7, 9]]
Matriz: 
[[8 7 9]]
Promedio: [8. 7. 9.]
Puntajes: [24]
Seleccionado: Jose


In [160]:
pasantes = ''
a, b, c, d, e = reto_4(pasantes)
a = f"Resultados: {a}"
b = f"Matriz: \n{b}"
c = f"Promedio: {c}"
d = f"Puntajes: {d}"
e = f"Seleccionado: {e}"
print(a, b, c, d, e, sep='\n')

Resultados: None
Matriz: 
None
Promedio: None
Puntajes: None
Seleccionado: None
